# Generated by Django 5.1.1 on 2024-12-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NomorHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noHp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggalLahir', models.DateField()),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaToko', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judulBuku', models.CharField(max_length=200)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahunPenerbit', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoadmin.genre')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoadmin.penulis')),
            ],
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('pekerjaan', models.CharField(max_length=100)),
                ('tanggalLahir', models.DateField()),
                ('noHp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoadmin.nomorhp')),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('idPem', models.AutoField(primary_key=True, serialize=False)),
                ('waktuPembelian', models.DateTimeField()),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoadmin.pembeli')),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoadmin.toko')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlahPieces', models.IntegerField()),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoadmin.buku')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoadmin.pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='GudangToko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.IntegerField()),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoadmin.buku')),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokoadmin.toko')),
            ],
        ),
    ]
